import { IMAGE_PATH_TREE, loadImage, IMAGE_PATH_MUSHROOM, IMAGE_PATH_CITIZEN, IMAGE_PATH_CITIZEN_HOUSE, IMAGE_PATH_BUILDING_MARKET, IMAGE_PATH_AXE, IMAGE_PATH_BASKET, IMAGE_PATH_HELMET, IMAGE_PATH_TREE_LOG, IMAGE_PATH_WOOD_PLANK, IMAGE_PATH_CITIZEN_DEAD, IMAGE_PATH_HAMMER, IMAGE_PATH_CITIZEN_SLEEPING, IMAGE_PATH_CITIZEN_EAT, IMAGE_PATH_MONEY, IMAGE_PATH_CITIZEN_PART_BODY, IMAGE_PATH_CITIZEN_PART_EAR_LEFT, IMAGE_PATH_CITIZEN_PART_EAR_RIGHT, IMAGE_PATH_CITIZEN_PART_EAR_SIDE, IMAGE_PATH_CITIZEN_PART_FOOT, IMAGE_PATH_CITIZEN_PART_HEAD, IMAGE_PATH_CITIZEN_PART_HEAD_SIDE, IMAGE_PATH_CITIZEN_PART_PAW } from "../drawHelper.js";

export const IMAGES: { [key: string]: HTMLImageElement } = {
}

export function loadImages() {
    const images: string[] = [
        IMAGE_PATH_TREE,
        IMAGE_PATH_MUSHROOM,
        IMAGE_PATH_CITIZEN,
        IMAGE_PATH_CITIZEN_HOUSE,
        IMAGE_PATH_CITIZEN_SLEEPING,
        IMAGE_PATH_CITIZEN_EAT,
        IMAGE_PATH_BUILDING_MARKET,
        IMAGE_PATH_AXE,
        IMAGE_PATH_BASKET,
        IMAGE_PATH_HELMET,
        IMAGE_PATH_TREE_LOG,
        IMAGE_PATH_WOOD_PLANK,
        IMAGE_PATH_CITIZEN_DEAD,
        IMAGE_PATH_HAMMER,
        IMAGE_PATH_MONEY,
        IMAGE_PATH_CITIZEN_PART_BODY,
        IMAGE_PATH_CITIZEN_PART_EAR_LEFT,
        IMAGE_PATH_CITIZEN_PART_EAR_RIGHT,
        IMAGE_PATH_CITIZEN_PART_EAR_SIDE,
        IMAGE_PATH_CITIZEN_PART_FOOT,
        IMAGE_PATH_CITIZEN_PART_HEAD,
        IMAGE_PATH_CITIZEN_PART_HEAD_SIDE,
        IMAGE_PATH_CITIZEN_PART_PAW,
    ]

    for (let image of images) {
        IMAGES[image] = loadImage(image);
    }
}
