import { IMAGE_PATH_TREE, loadImage, IMAGE_PATH_MUSHROOM, IMAGE_PATH_CITIZEN, IMAGE_PATH_CITIZEN_HOUSE, IMAGE_PATH_BUILDING_MARKET, IMAGE_PATH_AXE, IMAGE_PATH_BASKET, IMAGE_PATH_HELMET, IMAGE_PATH_TREE_LOG, IMAGE_PATH_WOOD_PLANK } from "../drawHelper.js";
import { ChatSimState } from "./chatSimModels.js";

export const IMAGES: { [key: string]: HTMLImageElement } = {
}

export function loadImages(state: ChatSimState) {
    IMAGES[IMAGE_PATH_TREE] = loadImage(IMAGE_PATH_TREE);
    IMAGES[IMAGE_PATH_MUSHROOM] = loadImage(IMAGE_PATH_MUSHROOM);
    IMAGES[IMAGE_PATH_CITIZEN] = loadImage(IMAGE_PATH_CITIZEN);
    IMAGES[IMAGE_PATH_CITIZEN_HOUSE] = loadImage(IMAGE_PATH_CITIZEN_HOUSE);
    IMAGES[IMAGE_PATH_BUILDING_MARKET] = loadImage(IMAGE_PATH_BUILDING_MARKET);
    IMAGES[IMAGE_PATH_AXE] = loadImage(IMAGE_PATH_AXE);
    IMAGES[IMAGE_PATH_BASKET] = loadImage(IMAGE_PATH_BASKET);
    IMAGES[IMAGE_PATH_HELMET] = loadImage(IMAGE_PATH_HELMET);
    IMAGES[IMAGE_PATH_TREE_LOG] = loadImage(IMAGE_PATH_TREE_LOG);
    IMAGES[IMAGE_PATH_WOOD_PLANK] = loadImage(IMAGE_PATH_WOOD_PLANK);
}
